### ISSUE TITLE
Folder /etc/nagios3/conf.d/ doesn't exist

### ISSUE THREAD

**Issue by doque** [dpiquet/pve-monitor#17]
I've installed nagios according to [this tutorial](http://nagios.sourceforge.net/docs/3_0/quickstart-ubuntu.html). But I don't have the folder `/etc/nagios3/conf.d/` present, as described in [this step in the wiki](https://github.com/dpiquet/pve-monitor/wiki#define-your-cluster-in-nagios-configuration).

I'm also unsure where to put the configuration file that is [mentioned here](https://github.com/dpiquet/pve-monitor/wiki#describe-your-cluster-in-the-configuration-file).

The nagios version I'm using is Nagios® Core™ 4.0.8.

Thank you!

**Comment by dpiquet** [comment]
Hi,

The wiki was written for the packaged version of Nagios. It seems the installation from sources you have done put the files into /usr/local/nagios/.

You should find a directory called plugins in there. Drop the plugin with the others and don't forget to adapt the path in the commands configuration.

You can drop pve-monitor's configuration file wherever you want as long as it is readable by Nagios. I use to put it with the Nagios configuration files (usually /etc/nagios3/; probably /usr/local/nagios/etc/).

**Comment by doque** [comment]
Thank you.
