### ISSUE TITLE
Could not connect to any server !

### ISSUE THREAD

**Issue by informatique-nemo** [dpiquet/pve-monitor#23]
Bonjour
j'ai deux soucis
si j'utilise la version 1.05 

/usr/bin/perl /usr/local/nagios/libexec/pve-monitor.pl --conf /usr/local/nagios/libexec/pve-monitor.conf --nodes --debug

Setting timeout to 5
Loaded node amphiprion3
Loaded openvz example
Loaded qemu msvm
Loaded storage local
Loaded pool Sample
Trying 192.168.17.3...
DEBUG: login not successful
DEBUG: 401 authentication failure

------------------------

node amphiprion3 {
    address 192.168.17.3
    port 8006 # Optional, default is 8006
    monitor_account     root
    monitor_password    XXXXXXXXXX
    realm pve # Optional, default is pam
    mem 80 90 # optional, not monitored if not defined
    cpu 80 95 # optional
    disk 80 90 # optional
}

=====================
soucis N° 2 si j'utilise la derriere version

Bareword found where operator expected at /usr/local/nagios/libexec/pve-monitor-1.4.pl line 5, near ""en" class"
        (Missing operator before class?)
Bareword found where operator expected at /usr/local/nagios/libexec/pve-monitor-1.4.pl line 13, near "<title>pve"
        (Missing operator before pve?)
Can't modify numeric lt (<) in scalar assignment at /usr/local/nagios/libexec/pve-monitor-1.4.pl line 5, near ""en" class"
syntax error at /usr/local/nagios/libexec/pve-monitor-1.4.pl line 5, near ""en" class"
Unrecognized character \xC2; marked by <-- HERE after at master <-- HERE near column 49 at /usr/local/nagios/libexec/pve-monitor-1.4.pl line 13.

des idées ??

**Comment by dpiquet** [comment]
Bonjour,

Avez vous installé le module Net::Proxmox::VE depuis cpan ou depuis mon fork github (https://github.com/dpiquet/proxmox-ve-api-perl) ? Ces deux versions sont différentes, pve-monitor 1.05 ne fonctionne qu'avec ma version du module.

Je viens de publier une nouvelle version de pve-monitor (1.06) qui utilise la version cpan du module, ce qui sera la norme pour les futures versions. Si vous avez installé Net::Proxmox::VE en utilisant cpan, je vous invite a utiliser cette nouvelle version.

La version 1.4 a été mal nommée et est en fait antérieure a la version 1.05. J'ai supprimé cette version pour éviter toute future confusion.

**Comment by informatique-nemo** [comment]
bonjour,

je vous remercie d'avoir pris le temps de me répondre.

non, effectivement, je n'avais pas installé correctement via CPAN le module.
c'est fait :



***************************************************************************
***************************************************************************
cpan[1]> install Net::Proxmox::VE
Going to read '/root/.cpan/Metadata'
   Database was generated on Wed, 29 Jul 2015 13:29:02 GMT
Fetching with LWP:
http://ftp.nluug.nl/languages/perl/CPAN/authors/01mailrc.txt.gz
Going to read '/root/.cpan/sources/authors/01mailrc.txt.gz'
............................................................................DONE
Fetching with LWP:
http://ftp.nluug.nl/languages/perl/CPAN/modules/02packages.details.txt.gz
Going to read '/root/.cpan/sources/modules/02packages.details.txt.gz'
   Database was generated on Thu, 27 Aug 2015 09:41:02 GMT
..............
   New CPAN.pm version (v2.10) available.
   [Currently running version is v1.960001]
   You might want to try
     install CPAN
     reload cpan
   to both upgrade CPAN.pm and run the new version without leaving
   the current session.


..............................................................DONE
Fetching with LWP:
http://ftp.nluug.nl/languages/perl/CPAN/modules/03modlist.data.gz
Going to read '/root/.cpan/sources/modules/03modlist.data.gz'
DONE
Going to write /root/.cpan/Metadata
Running install for module 'Net::Proxmox::VE'
Running make for D/DJ/DJZORT/Net-Proxmox-VE-0.0092.tar.gz
Fetching with LWP:
http://ftp.nluug.nl/languages/perl/CPAN/authors/id/D/DJ/DJZORT/Net-Proxmox-VE-0. 
0092.tar.gz
Fetching with LWP:
http://ftp.nluug.nl/languages/perl/CPAN/authors/id/D/DJ/DJZORT/CHECKSUMS
Checksum for 
/root/.cpan/sources/authors/id/D/DJ/DJZORT/Net-Proxmox-VE-0.0092.ta r.gz ok
Scanning cache /root/.cpan/build for sizes
............................................................................DONE

   CPAN.pm: Going to build D/DJ/DJZORT/Net-Proxmox-VE-0.0092.tar.gz

Checking prerequisites...
   test_requires:
     !  Test::Trap is not installed

ERRORS/WARNINGS FOUND IN PREREQUISITES.  You may wish to install the 
versions
of the modules indicated above before proceeding with this installation

Created MYMETA.yml and MYMETA.json
Creating new 'Build' script for 'Net-Proxmox-VE' version '0.0092'
---- Unsatisfied dependencies detected during ----
----    DJZORT/Net-Proxmox-VE-0.0092.tar.gz   ----
     Test::Trap [build_requires]
Running Build test
   Delayed until after prerequisites
Running Build install
   Delayed until after prerequisites
Running install for module 'Test::Trap'
Running make for E/EB/EBHANSSEN/Test-Trap-v0.3.2.tar.gz
Fetching with LWP:
http://ftp.nluug.nl/languages/perl/CPAN/authors/id/E/EB/EBHANSSEN/Test-Trap-v0.3 
.2.tar.gz
Fetching with LWP:
http://ftp.nluug.nl/languages/perl/CPAN/authors/id/E/EB/EBHANSSEN/CHECKSUMS
Checksum for 
/root/.cpan/sources/authors/id/E/EB/EBHANSSEN/Test-Trap-v0.3.2.tar. gz ok

   CPAN.pm: Going to build E/EB/EBHANSSEN/Test-Trap-v0.3.2.tar.gz

Checking prerequisites...
   requires:
     !  Data::Dump is not installed
     !  Test::Tester is not installed

ERRORS/WARNINGS FOUND IN PREREQUISITES.  You may wish to install the 
versions
of the modules indicated above before proceeding with this installation

Created MYMETA.yml and MYMETA.json
Creating new 'Build' script for 'Test-Trap' version 'v0.3.2'
---- Unsatisfied dependencies detected during ----
----     EBHANSSEN/Test-Trap-v0.3.2.tar.gz    ----
     Test::Tester [requires]
     Data::Dump [requires]
Running Build test
   Delayed until after prerequisites
Running Build install
   Delayed until after prerequisites
Running install for module 'Test::Tester'
Running make for E/EX/EXODIST/Test-Simple-1.001014.tar.gz
Fetching with LWP:
http://ftp.nluug.nl/languages/perl/CPAN/authors/id/E/EX/EXODIST/Test-Simple-1.00 
1014.tar.gz
Fetching with LWP:
http://ftp.nluug.nl/languages/perl/CPAN/authors/id/E/EX/EXODIST/CHECKSUMS
Checksum for 
/root/.cpan/sources/authors/id/E/EX/EXODIST/Test-Simple-1.001014.ta r.gz ok

   CPAN.pm: Going to build E/EX/EXODIST/Test-Simple-1.001014.tar.gz

Checking if your kit is complete...
Looks good
Generating a Unix-style Makefile
Writing Makefile for Test::Simple
Writing MYMETA.yml and MYMETA.json
cp lib/Test/Tester/Capture.pm blib/lib/Test/Tester/Capture.pm
cp lib/Test/Tester.pm blib/lib/Test/Tester.pm
cp lib/Test/Builder/Tester/Color.pm blib/lib/Test/Builder/Tester/Color.pm
cp lib/ok.pm blib/lib/ok.pm
cp lib/Test/Simple.pm blib/lib/Test/Simple.pm
cp lib/Test/Builder/IO/Scalar.pm blib/lib/Test/Builder/IO/Scalar.pm
cp lib/Test/Builder/Tester.pm blib/lib/Test/Builder/Tester.pm
cp lib/Test/Builder/Module.pm blib/lib/Test/Builder/Module.pm
cp lib/Test/Tutorial.pod blib/lib/Test/Tutorial.pod
cp lib/Test/use/ok.pm blib/lib/Test/use/ok.pm
cp lib/Test/Tester/CaptureRunner.pm blib/lib/Test/Tester/CaptureRunner.pm
cp lib/Test/Builder.pm blib/lib/Test/Builder.pm
cp lib/Test/Tester/Delegate.pm blib/lib/Test/Tester/Delegate.pm
cp lib/Test/More.pm blib/lib/Test/More.pm
Manifying 13 pod documents
   EXODIST/Test-Simple-1.001014.tar.gz
   make -- OK
'YAML' not installed, will not store persistent state
Running make test
PERL_DL_NONLAZY=1 "/usr/bin/perl" "-MExtUtils::Command::MM" 
"-MTest::Harness" "-                                      e" "undef 
*Test::Harness::Switches; test_harness(0, 'blib/lib', 'blib/arch')" 
t/                                      *.t t/*/*.t
t/00compile.t ........................... 1/24 You should load 
Test::Tester befo                                      re Test::Builder 
(or anything that loads Test::Builder) at Test/Tester.pm line 
9                                      .
t/00compile.t ........................... ok
t/00test_harness_check.t ................ ok
t/01-basic.t ............................ ok
t/478-cmp_ok_hash.t ..................... ok
t/auto.t ................................ ok
t/bad_plan.t ............................ ok
t/bail_out.t ............................ ok
t/BEGIN_require_ok.t .................... ok
t/BEGIN_use_ok.t ........................ ok
t/buffer.t .............................. ok
t/Builder/Builder.t ..................... ok
t/Builder/carp.t ........................ ok
t/Builder/create.t ...................... ok
t/Builder/current_test.t ................ ok
t/Builder/current_test_without_plan.t ... ok
t/Builder/details.t ..................... ok
t/Builder/done_testing.t ................ ok
t/Builder/done_testing_double.t ......... ok
t/Builder/done_testing_plan_mismatch.t .. ok
t/Builder/done_testing_with_no_plan.t ... ok
t/Builder/done_testing_with_number.t .... ok
t/Builder/done_testing_with_plan.t ...... ok
t/Builder/fork_with_new_stdout.t ........ ok
t/Builder/has_plan.t .................... ok
t/Builder/has_plan2.t ................... ok
t/Builder/is_fh.t ....................... ok
t/Builder/is_passing.t .................. ok
t/Builder/maybe_regex.t ................. ok
t/Builder/no_diag.t ..................... ok
t/Builder/no_ending.t ................... ok
t/Builder/no_header.t ................... ok
t/Builder/no_plan_at_all.t .............. ok
t/Builder/ok_obj.t ...................... ok
t/Builder/output.t ...................... ok
t/Builder/reset.t ....................... ok
t/Builder/reset_outputs.t ............... ok
t/Builder/try.t ......................... ok
t/c_flag.t .............................. ok
t/capture.t ............................. ok
t/check_tests.t ......................... ok
t/circular_data.t ....................... ok
t/cmp_ok.t .............................. ok
t/dependents.t .......................... skipped: Dependents only 
tested when r                                      eleasing
t/depth.t ............................... ok
t/diag.t ................................ ok
t/died.t ................................ ok
t/dont_overwrite_die_handler.t .......... ok
t/eq_set.t .............................. ok
t/exit.t ................................ ok
t/explain.t ............................. ok
t/extra.t ............................... ok
t/extra_one.t ........................... ok
t/fail-like.t ........................... ok
t/fail-more.t ........................... ok
t/fail.t ................................ ok
t/fail_one.t ............................ ok
t/filehandles.t ......................... ok
t/fork.t ................................ ok
t/harness_active.t ...................... ok
t/import.t .............................. ok
t/is_deeply_dne_bug.t ................... ok
t/is_deeply_fail.t ...................... ok
t/is_deeply_with_threads.t .............. skipped: many perls have 
broken thread                                      s.  Enable with 
AUTHOR_TESTING.
t/missing.t ............................. ok
t/More.t ................................ ok
t/new_ok.t .............................. ok
t/no_plan.t ............................. ok
t/no_tests.t ............................ ok
t/note.t ................................ ok
t/overload.t ............................ ok
t/overload_threads.t .................... ok
t/plan.t ................................ ok
t/plan_bad.t ............................ ok
t/plan_is_noplan.t ...................... ok
t/plan_no_plan.t ........................ ok
t/plan_shouldnt_import.t ................ ok
t/plan_skip_all.t ....................... skipped: Just testing plan & 
skip_all
t/require_ok.t .......................... ok
t/run_test.t ............................ ok
t/simple.t .............................. ok
t/Simple/load.t ......................... ok
t/skip.t ................................ ok
t/skipall.t ............................. ok
t/subtest/args.t ........................ ok
t/subtest/bail_out.t .................... ok
t/subtest/basic.t ....................... ok
t/subtest/die.t ......................... ok
t/subtest/do.t .......................... ok
t/subtest/exceptions.t .................. ok
t/subtest/fork.t ........................ ok
t/subtest/implicit_done.t ............... ok
t/subtest/line_numbers.t ................ ok
t/subtest/plan.t ........................ ok
t/subtest/predicate.t ................... ok
t/subtest/singleton.t ................... ok
t/subtest/threads.t ..................... ok
t/subtest/todo.t ........................ ok
t/subtest/wstat.t ....................... ok
t/tbm_doesnt_set_exported_to.t .......... ok
t/Tester/tbt_01basic.t .................. ok
t/Tester/tbt_02fhrestore.t .............. ok
t/Tester/tbt_03die.t .................... ok
t/Tester/tbt_04line_num.t ............... ok
t/Tester/tbt_05faildiag.t ............... ok
t/Tester/tbt_06errormess.t .............. ok
t/Tester/tbt_07args.t ................... ok
t/Tester/tbt_08subtest.t ................ ok
t/Tester/tbt_09do.t ..................... ok
t/thread_taint.t ........................ ok
t/threads.t ............................. ok
t/todo.t ................................ ok
t/undef.t ............................... ok
t/use_ok.t .............................. ok
t/useing.t .............................. ok
t/utf8.t ................................ ok
t/versions.t ............................ ok
t/xt/dependents.t ....................... skipped: Dependents only 
tested when r                                      eleasing
t/xxx-changes_updated.t ................. skipped: Only tested when 
releasing
All tests successful.
Files=118, Tests=1378,  6 wallclock secs ( 0.84 usr  0.22 sys + 4.42 
cusr  0.78                                       csys =  6.26 CPU)
Result: PASS
   EXODIST/Test-Simple-1.001014.tar.gz
   make test -- OK
Running make install
Manifying 13 pod documents
Installing /usr/local/share/perl/5.14.2/ok.pm
Installing /usr/local/share/perl/5.14.2/Test/More.pm
Installing /usr/local/share/perl/5.14.2/Test/Builder.pm
Installing /usr/local/share/perl/5.14.2/Test/Tester.pm
Installing /usr/local/share/perl/5.14.2/Test/Tutorial.pod
Installing /usr/local/share/perl/5.14.2/Test/Simple.pm
Installing /usr/local/share/perl/5.14.2/Test/Builder/Tester.pm
Installing /usr/local/share/perl/5.14.2/Test/Builder/Module.pm
Installing /usr/local/share/perl/5.14.2/Test/Builder/IO/Scalar.pm
Installing /usr/local/share/perl/5.14.2/Test/Builder/Tester/Color.pm
Installing /usr/local/share/perl/5.14.2/Test/use/ok.pm
Installing /usr/local/share/perl/5.14.2/Test/Tester/CaptureRunner.pm
Installing /usr/local/share/perl/5.14.2/Test/Tester/Delegate.pm
Installing /usr/local/share/perl/5.14.2/Test/Tester/Capture.pm
Installing /usr/local/man/man3/Test::Builder::Tester.3pm
Installing /usr/local/man/man3/Test::Builder::IO::Scalar.3pm
Installing /usr/local/man/man3/Test::Tester.3pm
Installing /usr/local/man/man3/Test::Simple.3pm
Installing /usr/local/man/man3/Test::Builder::Tester::Color.3pm
Installing /usr/local/man/man3/Test::use::ok.3pm
Installing /usr/local/man/man3/Test::Builder::Module.3pm
Installing /usr/local/man/man3/Test::Tester::Capture.3pm
Installing /usr/local/man/man3/ok.3pm
Installing /usr/local/man/man3/Test::Tester::CaptureRunner.3pm
Installing /usr/local/man/man3/Test::More.3pm
Installing /usr/local/man/man3/Test::Tutorial.3pm
Installing /usr/local/man/man3/Test::Builder.3pm
Appending installation info to /usr/lib/perl/5.14/perllocal.pod
   EXODIST/Test-Simple-1.001014.tar.gz
   make install  -- OK
Running install for module 'Data::Dump'
Running make for G/GA/GAAS/Data-Dump-1.23.tar.gz
Fetching with LWP:
http://ftp.nluug.nl/languages/perl/CPAN/authors/id/G/GA/GAAS/Data-Dump-1.23.tar. 
gz
Fetching with LWP:
http://ftp.nluug.nl/languages/perl/CPAN/authors/id/G/GA/GAAS/CHECKSUMS
Checksum for 
/root/.cpan/sources/authors/id/G/GA/GAAS/Data-Dump-1.23.tar.gz ok

   CPAN.pm: Going to build G/GA/GAAS/Data-Dump-1.23.tar.gz

Checking if your kit is complete...
Looks good
Generating a Unix-style Makefile
Writing Makefile for Data::Dump
Writing MYMETA.yml and MYMETA.json
cp lib/Data/Dump.pm blib/lib/Data/Dump.pm
cp lib/Data/Dump/FilterContext.pm blib/lib/Data/Dump/FilterContext.pm
cp lib/Data/Dump/Trace.pm blib/lib/Data/Dump/Trace.pm
cp lib/Data/Dump/Filtered.pm blib/lib/Data/Dump/Filtered.pm
Manifying 3 pod documents
   GAAS/Data-Dump-1.23.tar.gz
   make -- OK
Running make test
PERL_DL_NONLAZY=1 "/usr/bin/perl" "-MExtUtils::Command::MM" 
"-MTest::Harness" "-                                      e" "undef 
*Test::Harness::Switches; test_harness(0, 'blib/lib', 'blib/arch')" 
t/                                      *.t
t/dd.t ............. ok
t/dollar-one.t ..... ok
t/dump.t ........... ok
t/eval.t ........... ok
t/filtered.t ....... ok
t/glob.t ........... ok
t/hash.t ........... ok
t/quote-unicode.t .. ok
t/quote.t .......... ok
t/ref.t ............ ok
t/regexp.t ......... ok
t/scalar-obj.t ..... ok
t/scalar.t ......... ok
t/tied.t ........... ok
t/vstring.t ........ ok
All tests successful.
Files=15, Tests=145,  1 wallclock secs ( 0.11 usr  0.03 sys +  0.38 
cusr  0.09 c                                      sys =  0.61 CPU)
Result: PASS
   GAAS/Data-Dump-1.23.tar.gz
   make test -- OK
Running make install
Manifying 3 pod documents
Installing /usr/local/share/perl/5.14.2/Data/Dump.pm
Installing /usr/local/share/perl/5.14.2/Data/Dump/Trace.pm
Installing /usr/local/share/perl/5.14.2/Data/Dump/Filtered.pm
Installing /usr/local/share/perl/5.14.2/Data/Dump/FilterContext.pm
Installing /usr/local/man/man3/Data::Dump::Trace.3pm
Installing /usr/local/man/man3/Data::Dump.3pm
Installing /usr/local/man/man3/Data::Dump::Filtered.3pm
Appending installation info to /usr/lib/perl/5.14/perllocal.pod
   GAAS/Data-Dump-1.23.tar.gz
   make install  -- OK
Running Build for E/EB/EBHANSSEN/Test-Trap-v0.3.2.tar.gz
   Has already been unwrapped into directory 
/root/.cpan/build/Test-Trap-v0.3.2-z skNT0

   CPAN.pm: Going to build E/EB/EBHANSSEN/Test-Trap-v0.3.2.tar.gz

Building Test-Trap
   EBHANSSEN/Test-Trap-v0.3.2.tar.gz
   ./Build -- OK
Running Build test
t/00-load.t ....................... 1/5 # Testing Test::Trap 0.3.2, Perl 
5.01400                                      2, /usr/bin/perl
t/00-load.t ....................... ok
t/01-basic.t ...................... ok
t/02-reentrant.t .................. ok
t/03-files-perlio.t ............... ok
t/03-files-systemsafe-preserve.t .. ok
t/03-files-systemsafe.t ........... ok
t/03-files-tempfile-preserve.t .... ok
t/03-files-tempfile.t ............. ok
t/04-exit.t ....................... ok
t/05-import.t ..................... ok
t/06-layers.t ..................... ok
t/07-subclass.t ................... ok
t/08-fork.t ....................... # Real fork; taint checks enabled
t/08-fork.t ....................... ok
t/09-array-accessor.t ............. ok
t/10-tester.t ..................... ok
t/11-systemsafe-basic.t ........... # Real fork; taint checks enabled
t/11-systemsafe-basic.t ........... ok
t/12-systemsafe-errors.t .......... ok
t/13-regressions.t ................ ok
t/14-leaks.t ...................... skipped: Test::Refcount and 
Scalar::Util req                                      uired to test refcount
t/15-tempfile-options.t ........... ok
t/16-systemsafe-options.t ......... ok
t/99-coverage.t ................... ok
All tests successful.
Files=22, Tests=1129,  4 wallclock secs ( 0.38 usr  0.06 sys +  2.54 
cusr  0.28                                       csys =  3.26 CPU)
Result: PASS
   EBHANSSEN/Test-Trap-v0.3.2.tar.gz
   ./Build test -- OK
Running Build install
Building Test-Trap
Installing /usr/local/share/perl/5.14.2/Test/Trap.pm
Installing /usr/local/share/perl/5.14.2/Test/Trap/Builder.pm
Installing /usr/local/share/perl/5.14.2/Test/Trap/Builder/PerlIO.pm
Installing /usr/local/share/perl/5.14.2/Test/Trap/Builder/TempFile.pm
Installing /usr/local/share/perl/5.14.2/Test/Trap/Builder/SystemSafe.pm
Installing /usr/local/man/man3/Test::Trap::Builder::TempFile.3pm
Installing /usr/local/man/man3/Test::Trap::Builder::SystemSafe.3pm
Installing /usr/local/man/man3/Test::Trap::Builder.3pm
Installing /usr/local/man/man3/Test::Trap.3pm
Installing /usr/local/man/man3/Test::Trap::Builder::PerlIO.3pm
   EBHANSSEN/Test-Trap-v0.3.2.tar.gz
   ./Build install  -- OK
Running Build for D/DJ/DJZORT/Net-Proxmox-VE-0.0092.tar.gz
   Has already been unwrapped into directory 
/root/.cpan/build/Net-Proxmox-VE-0.0 092-p3d7UR

   CPAN.pm: Going to build D/DJ/DJZORT/Net-Proxmox-VE-0.0092.tar.gz

Building Net-Proxmox-VE
   DJZORT/Net-Proxmox-VE-0.0092.tar.gz
   ./Build -- OK
Running Build test
t/00.load.t ................. 1/1 # Testing Net::Proxmox::VE 0.009, Perl 
5.01400                                      2, /usr/bin/perl
t/00.load.t ................. ok
t/101.proxmox-ve-new.t ...... skipped: This test sucks.  Set 
$ENV{PROXMOX_TEST_U                                      RI} to a real 
running proxmox to run.
t/120.proxmox-ve-access.t ... skipped: This test sucks.  Set 
$ENV{PROXMOX_TEST_U                                      RI} to a real 
running proxmox to run.
t/150-proxmox-ve-pools.t .... skipped: This test sucks.  Set 
$ENV{PROXMOX_TEST_U                                      RI} to a real 
running proxmox to run.
t/160-proxmox-ve-storage.t .. skipped: This test sucks.  Set 
$ENV{PROXMOX_TEST_U                                      RI} to a real 
running proxmox to run.
t/author-critic.t ........... skipped: these tests are for testing by 
the author
t/author-eol.t .............. skipped: these tests are for testing by 
the author
t/release-distmeta.t ........ skipped: these tests are for release 
candidate tes                                      ting
t/release-kwalitee.t ........ skipped: these tests are for release 
candidate tes                                      ting
t/release-pod-coverage.t .... skipped: these tests are for release 
candidate tes                                      ting
t/release-pod-syntax.t ...... skipped: these tests are for release 
candidate tes                                      ting
All tests successful.
Files=11, Tests=1,  1 wallclock secs ( 0.07 usr  0.02 sys +  0.60 cusr  
0.07 csy                                      s =  0.76 CPU)
Result: PASS
   DJZORT/Net-Proxmox-VE-0.0092.tar.gz
   ./Build test -- OK
Running Build install
Building Net-Proxmox-VE
Installing /usr/local/share/perl/5.14.2/Net/Proxmox/VE.pm
Installing /usr/local/share/perl/5.14.2/Net/Proxmox/VE/Pools.pm
Installing /usr/local/share/perl/5.14.2/Net/Proxmox/VE/Storage.pm
Installing /usr/local/share/perl/5.14.2/Net/Proxmox/VE/Cluster.pm
Installing /usr/local/share/perl/5.14.2/Net/Proxmox/VE/Nodes.pm
Installing /usr/local/share/perl/5.14.2/Net/Proxmox/VE/Access.pm
Installing /usr/local/man/man3/Net::Proxmox::VE::Cluster.3pm
Installing /usr/local/man/man3/Net::Proxmox::VE::Pools.3pm
Installing /usr/local/man/man3/Net::Proxmox::VE::Storage.3pm
Installing /usr/local/man/man3/Net::Proxmox::VE::Access.3pm
Installing /usr/local/man/man3/Net::Proxmox::VE.3pm
Installing /usr/local/man/man3/Net::Proxmox::VE::Nodes.3pm
   DJZORT/Net-Proxmox-VE-0.0092.tar.gz
   ./Build install  -- OK


***************************************************************************
***************************************************************************

j ai aussi mis a jour en version 1.06



Or,
tjrs meme soucis...

root@nagios4:~# /usr/bin/perl /usr/local/nagios/libexec/pve-monitor.pl 
--conf /usr/local/nagios/libexec/pve-monitor.conf --nodes --debug
Starting pve-monitor 1.06
Setting timeout to 5
Loaded node amphiprion3
Loaded openvz example
Loaded qemu msvm
Loaded storage local
Loaded pool Sample
Trying 192.168.17.3...
DEBUG: login not successful
DEBUG: 401 authentication failure

******************

Pour rappel, mon fichier de conf :

node amphiprion3 {
     address 192.168.17.3
     port 8006 # Optional, default is 8006
     monitor_account     root
     monitor_password    a2nemo1234
     realm pve # Optional, default is pam
     mem 80 90 # optional, not monitored if not defined
     cpu 80 95 # optional
     disk 80 90 # optional
}

# openvz example
openvz example {
     mem 80 90
     cpu 80 95
     disk 80 90
}

# qemu example
qemu msvm {
     mem 80 90
     cpu 80 95
     disk 80 90
}

#storage example
storage local {
     disk 80 90
     node Amphiprion3
}

#pool example
pool Sample {
     mem 98 100
     cpu 90 95
     disk 90 95
}

******************

Une idée de ce qui pourrais bloqué, peut être sur le serveur Proxmox ???

en sachant que :

root@amphiprion3:~# netstat -tupl
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address State       
PID/Program name
tcp        0      0 *:nrpe                  *:* LISTEN      2040/nrpe
tcp        0      0 *:8006                  *:* LISTEN      2305/pveproxy


Cordialement.



Le 27/08/2015 12:13, Damien PIQUET a écrit :
>
> Bonjour,
>
> Avez vous installé le module Net::Proxmox::VE depuis cpan ou depuis 
> mon fork github (https://github.com/dpiquet/proxmox-ve-api-perl) ? Ces 
> deux versions sont différentes, pve-monitor 1.05 ne fonctionne qu'avec 
> ma version du module.
>
> Je viens de publier une nouvelle version de pve-monitor (1.06) qui 
> utilise la version cpan du module, ce qui sera la norme pour les 
> futures versions. Si vous avez installé Net::Proxmox::VE en utilisant 
> cpan, je vous invite a utiliser cette nouvelle version.
>
> La version 1.4 a été mal nommée et est en fait antérieure a la version 
> 1.05. J'ai supprimé cette version pour éviter toute future confusion.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/dpiquet/pve-monitor/issues/23#issuecomment-135371169>.
>

-- 

Cordialement,
Regards,


*/Sylvain SONNIER/*

[Service Informatique]
[Prestataire SOGETI France]
Tél. +33 (0) 4 37 40 25 13
Mail : sonnier.ext@nemo-rec.com <mailto:sonnier.ext@nemo-rec.com>

*GROUPE NEMO* **
14, Avenue Barthélémy Thimonnier
69300 Caluire et Cuire | France

**Comment by dpiquet** [comment]
Je vois que vous utilisez le compte root (ce que je déconseille pour un environnement de production)

Le compte root est en realm 'pam' et non pve (c'est un compte Linux et non un compte interne à l'interface Proxmox VE). Modifiez la directive realm de votre fichier de configuration: changez pve en pam cela devrait résoudre votre problème.

**Comment by informatique-nemo** [comment]
bonjour,
entre les vacances, et la reprise, je n'ai eu le temps de tester la 
modification, qu'il y a 5 minutes.
Effectivement, tout fonctionne.
je vous remercie, je n'aurais pas penser à ça du tout.

Ah, le compte "root", j'ai repris le service informatique depuis 
février, et vous n'imaginer même pas .....
je découvre encore chaque semaine des aberrations ! je corrige petit à 
petit.

Dans tous les cas, merci pour votre aide cordiale.



Le 28/08/2015 13:12, Damien PIQUET a écrit :
>
> Je vois que vous utilisez le compte root (ce que je déconseille pour 
> un environnement de production)
>
> Le compte root est en realm 'pam' et non pve (c'est un compte Linux et 
> non un compte interne à l'interface Proxmox VE). Modifiez la directive 
> realm de votre fichier de configuration: changez pve en pam cela 
> devrait résoudre votre problème.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/dpiquet/pve-monitor/issues/23#issuecomment-135742891>.
>

-- 

Cordialement,
Regards,


*/Sylvain SONNIER/*

[Service Informatique]
[Prestataire SOGETI France]
Tél. +33 (0) 4 37 40 25 13
Mail : sonnier.ext@nemo-rec.com <mailto:sonnier.ext@nemo-rec.com>

*GROUPE NEMO* **
14, Avenue Barthélémy Thimonnier
69300 Caluire et Cuire | France

**Comment by dpiquet** [comment]
Bonjour,

Content de savoir que tout fonctionne. Bon courage pour votre reprise. Je ferme donc ce bug.

Cordialement,

Damien

**Comment by lilp69** [comment]
Bonjour, j'ai exactement le même soucis.
J'ai créer un user sous Proxmox avec les droits Admin que j'utilise dans le fichier de conf avec une connexion de type realm.
Mais toujours l'erreur de connection. J'aimerais essayer votre VE via github, mais je ne sais pas comment l'installer.
