### ISSUE TITLE
pve4 support

### ISSUE THREAD

**Issue by dpiquet** [dpiquet/pve-monitor#25]
adapt pve-monitor to pve4

**Comment by fichte** [comment]
any progress on this?

**Comment by dpiquet** [comment]
Hi,

I have been late on this project because i did not have a lab for a while, but pve-monitor will be tested very soon against pve4. Someone already told me the plugin was running fine with very little modification to handle lxc in addition to openvz. Here is the diff he gave me:
```
860c860
< 	            case "openvz" {
---
> 	            case /openvz|lxc/ {
1009c1009
<         case "openvz" {
---
>         case /openvz|lxc/ {
```

**Comment by dpiquet** [comment]
Support added in master branch (commit 81). Release coming soon.

**Comment by dpiquet** [comment]
Support added in release 1.07
